import Head from "next/head";
import styles from "../styles/Home.module.css";
import Navbar from "../components/Navbar/NavbarAfterLogin";
import { Fragment } from "react";
import Baner from "../components/header/Baner";
import Footer from "../components/footer/Footer";
import Peler from "./api/index";


export async function getStaticProps() {
  const detail = await Peler()
  return { props: { detail } };
}

export default function Home({ detail }) {
  return (
    <Fragment>
      <div className="body">
        <div className={styles.container}>
          <Head>
            <title>Hire Jobs</title>
            <meta name="description" content="Generated by Hire Jobs" />
            <link rel="icon" href="/vercel.svg" />
          </Head>
          <Navbar />
          <Baner data={detail} />
        </div>
        <Footer />
      </div>
    </Fragment>
  );
}
