import Head from "next/head";
import Image from "next/image";
import styles from "../styles/Home.module.css";
import Navbar from "../components/Navbar/NavbarAfterLogin";
import { Fragment } from "react";
import Baner from "../components/header/Baner";
import Footer from "../components/footer/Footer";
import axios from "axios";

export async function getStaticProps() {
  const result = await axios.get(`${process.env.API_BACKEND}review`);
  console.log(result.data);
  return { props: { detail: JSON.parse(JSON.stringify(result.data.data)) } };
}

export default function Home({ detail }) {
  console.log(detail);
  return (
    <Fragment>
      <div className="body">
        <div className={styles.container}>
          <Head>
            <title>Create Next App</title>
            <meta name="description" content="Generated by create next app" />
            <link rel="icon" href="/vercel.svg" />
          </Head>
          <Navbar />
          <Baner data={detail} />
        </div>
        <Footer />
      </div>
    </Fragment>
  );
}
