import Head from "next/head";
import Image from "next/image";
import styles from "../styles/Home.module.css";
import Navbar from "../components/Navbar/Navbar";
import { Fragment } from "react";
import Baner from "../components/header/Baner";
import Footer from "../components/footer/Footer";
import Peler from "./api/hello";

export async function getStaticProps() {
  const detail = await Peler()
  console.log(detail);
  return { props: { detail } };
}
export default function Home({detail}) {
  return (
    <Fragment>
      <div className="body">
        <div className={styles.container}>
          <Head>
            <title>Create Next App</title>
            <meta name="description" content="Generated by create next app" />
            <link rel="icon" href="/vercel.svg" />
          </Head>
          <Navbar />
          <Baner data={detail}/>
        </div>
        <Footer />
      </div>
    </Fragment>
  );
}
